version: '3.8'

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FRONTEND_URL=http://localhost:8080
      # Add your other environment variables here
      # - DATABASE_URL=
      # - OPENAI_API_KEY=
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://localhost:3000
    depends_on:
      - backend